modLoader = "javafml"
loaderVersion = "[40,)"
# issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs-extra-blocks"
version = "${version}"
displayName = "KubeJS Extra Blocks"
authors = "artemisSystem"
description = '''
Extra block types for KubeJS
'''
license = "GNU LGPLv3"

[[dependencies.kubejs-extra-blocks]]
modId = "kubejs"
mandatory = true
versionRange = "[1802.5.1-build.331,)"
ordering = "AFTER"
side = "BOTH"
